// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOkgawfIAs6Z5mLDCe-pfg_POe5K8q38',
    appId: '1:184330992881:web:ce9f27c6a8aecdb98d7d50',
    messagingSenderId: '184330992881',
    projectId: 'influ-inbox',
    authDomain: 'influ-inbox.firebaseapp.com',
    storageBucket: 'influ-inbox.firebasestorage.app',
    measurementId: 'G-1V7SX4P73S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNE72_qrLXSVD9JbQFTPTbciUpPnW6S0Y',
    appId: '1:184330992881:android:235dc90649c200438d7d50',
    messagingSenderId: '184330992881',
    projectId: 'influ-inbox',
    storageBucket: 'influ-inbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7roVB8c_winFFOwnM5a-OGXt7EClmWOU',
    appId: '1:184330992881:ios:6716c2e2242dc4348d7d50',
    messagingSenderId: '184330992881',
    projectId: 'influ-inbox',
    storageBucket: 'influ-inbox.firebasestorage.app',
    androidClientId: '184330992881-gmvpd9ckquh5sl63st4c4tnvjecj71l2.apps.googleusercontent.com',
    iosClientId: '184330992881-7mpphb9elkos19c338j8hcuiaalr1dok.apps.googleusercontent.com',
    iosBundleId: 'com.influinbox.influinbox',
  );
}
