import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:url_strategy/url_strategy.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'router.dart';
import 'features/theme/theme_screen.dart';

final counterProvider = StateProvider<int>((ref) => 0);

void main() async {
  setPathUrlStrategy();
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const ProviderScope(child: InfluInboxApp()));
}

class InfluInboxApp extends StatelessWidget {
  const InfluInboxApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Influinbox',
      theme: ThemeData(primarySwatch: Colors.blue),
      routerConfig: appRouter,
    );
  }
}

class HomePage extends ConsumerWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(counterProvider);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Influinbox'),
        actions: [
          IconButton(
            icon: const Icon(Icons.palette),
            tooltip: 'Theme Showcase',
            onPressed: () {
              Navigator.of(context).push(MaterialPageRoute(builder: (_) => const ThemeScreen()));
            },
          ),
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text('$count', style: Theme.of(context).textTheme.headlineMedium),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(onPressed: () => ref.read(counterProvider.notifier).state++, tooltip: 'Increment', child: const Icon(Icons.add)),
    );
  }
}
